bank-api-secrets.jwt-secret=4kLm2n8pX0rZ5yQ3sT9vW6qJ1eR8aD7f
bank-api-secrets.jwt-expiration=15d
bank-api-secrets.access-jwt-name=zentra_access_jwt
bank-api-secrets.refresh-jwt-name=zentra_refresh_jwt
bank-api-secrets.refresh-token-expiration=7d
bank-api-secrets.jwt-cookie-expireIn=90d
bank-api-secrets.profile-active=prod
bank-api-secrets.super-admin-email=admin@gmail.com
bank-api-secrets.super-admin-password=admin1234
bank-api-secrets.super-admin-first-name=Salim
bank-api-secrets.super-admin-last-name=Hassan

API_PREFIX=/api/v1

# DB
DB_HOST=zentrabank-db
DB_PORT=5432
POSTGRES_DB=zentrabank-db
POSTGRES_USER=admin
POSTGRES_PASSWORD=zentrabank-salim-db@19932409


# Server
DB_NAME=zentrabank-db
DB_USERNAME=admin
DB_PASSWORD=zentrabank-salim-db@19932409

